:notepad a.bat
doskey 1=ping google.com
doskey 1t=ping -t google.com
doskey 2=ping 8.8.8.8
doskey 2t=ping -t 8.8.8.8
doskey 7z="C:\Program Files\7-Zip\7z.exe" $*
doskey a=%USERPROFILE%\a.bat
doskey c=cls
doskey d=echo %date% (MM/DD/YYYY) -%time% GMT+8
doskey e=echo $*
doskey h=hostname
doskey i=netsh interface ip show config Ethernet
doskey ip=ipconfig
doskey ipa=ipconfig /all
doskey ia=ipconfig /all
doskey j=%USERPROFILE%\j.bat
doskey m=more
doskey n=notepad $*
doskey ne=netstat -ano $*
doskey p=ping $*
doskey p8=ping 8.8.8.8
doskey p8t=ping 8.8.8.8 -t
doskey pa=pathping $*
doskey pg=ping google.com
doskey pgt=ping google.com -t
doskey pr=netsh winhttp show proxy
doskey pu=curl ifconfig.me
doskey =echo %cd%
doskey re=shutdown -r -f -t 0
doskey sh=shutdown -s -f -t 0
doskey s="C:\Program Files (x86)\Sublime Text 3\sublime_text.exe" $*
doskey t=tracert $*
doskey w=whoami $*
